// Fallback Mock Data for instant zero-latency loading and serverless resilience
export const FALLBACK_PRODUCTS = [
  {
    id: "prod-1",
    slug: "mega-pack-5000-prompts-chatgpt-ia",
    title: "Mega Pack 5,000+ Prompts Avanzados de ChatGPT & Claude",
    description: "La biblioteca definitiva de ingeniería de prompts para automatizar marketing, ventas B2B, programación y generación de contenido viral.",
    shortDescription: "Domina la IA con más de 5,000 prompts probados para marketing, código y ventas.",
    coverImageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    price: 39.0,
    currencyCode: "USD",
    guaranteeDays: 14,
    affiliateEnabled: true,
    affiliateCommissionPct: 40.0,
    affiliateApprovalMode: "AUTO",
    salesCount: 1420,
    ratingAvg: 4.9,
    reviewsCount: 184,
    category: { name: "Prompts IA" },
    seller: {
      firstName: "Ignacio",
      lastName: "Morales",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "prod-2",
    slug: "saas-starter-kit-nextjs-14-stripe",
    title: "SaaS Starter Kit — Next.js 14, Stripe & Tailwind",
    description: "Boilerplate de producción listo para lanzar tu SaaS en menos de 48 horas con autenticación, facturación y panel de administración multi-tenant.",
    shortDescription: "Lanza tu software en 48 horas con auth, suscripciones Stripe y base de datos.",
    coverImageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80",
    price: 129.0,
    currencyCode: "USD",
    guaranteeDays: 30,
    affiliateEnabled: true,
    affiliateCommissionPct: 30.0,
    affiliateApprovalMode: "AUTO",
    salesCount: 890,
    ratingAvg: 5.0,
    reviewsCount: 92,
    category: { name: "Código y Scripts" },
    seller: {
      firstName: "Valeria",
      lastName: "Ríos",
      avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "prod-3",
    slug: "masterclass-agentes-ia-autonomos-python",
    title: "Masterclass: Creación de Agentes de IA Autónomos con Python",
    description: "Curso profesional paso a paso sobre construcción de agentes multi-herramienta usando LangChain, CrewAI y APIs de DeepSeek & OpenAI.",
    shortDescription: "Aprende a programar agentes autónomos que resuelven flujos complejos de trabajo.",
    coverImageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=80",
    price: 79.0,
    currencyCode: "USD",
    guaranteeDays: 7,
    affiliateEnabled: true,
    affiliateCommissionPct: 50.0,
    affiliateApprovalMode: "MANUAL",
    salesCount: 650,
    ratingAvg: 4.8,
    reviewsCount: 76,
    category: { name: "Cursos Online" },
    seller: {
      firstName: "Gabriel",
      lastName: "López",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "prod-4",
    slug: "design-system-figma-pro-200-componentes",
    title: "Sistema de Diseño Figma Pro — 200+ Componentes UI/UX",
    description: "Biblioteca UI completa para Figma con Auto Layout 5.0, variables de modo oscuro/claro y tokens de diseño para agencias y diseñadores.",
    shortDescription: "El sistema de diseño más completo para Figma con variables y dark mode.",
    coverImageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&auto=format&fit=crop&q=80",
    price: 49.0,
    currencyCode: "USD",
    guaranteeDays: 14,
    affiliateEnabled: true,
    affiliateCommissionPct: 35.0,
    affiliateApprovalMode: "AUTO",
    salesCount: 420,
    ratingAvg: 4.9,
    reviewsCount: 51,
    category: { name: "Plantillas Web" },
    seller: {
      firstName: "Camila",
      lastName: "Torres",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "prod-5",
    slug: "embudos-ventas-high-ticket-notion",
    title: "Sistema Operativo de Embudos High-Ticket en Notion",
    description: "Plantilla integral en Notion para gestionar leads cualificados, pipeline de llamadas de venta y seguimiento automatizado de clientes.",
    shortDescription: "Gestiona tu pipeline comercial y cierra ventas de alto valor en Notion.",
    coverImageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
    price: 29.0,
    currencyCode: "USD",
    guaranteeDays: 7,
    affiliateEnabled: true,
    affiliateCommissionPct: 25.0,
    affiliateApprovalMode: "AUTO",
    salesCount: 310,
    ratingAvg: 4.7,
    reviewsCount: 38,
    category: { name: "Finanzas y Negocios" },
    seller: {
      firstName: "Ignacio",
      lastName: "Morales",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "prod-6",
    slug: "kit-300-reels-virales-canva-editable",
    title: "Kit de 300+ Plantillas de Reels y TikToks en Canva",
    description: "Plantillas 100% editables con tipografías y animaciones de alta retención para creadores de contenido, marcas personales y negocios.",
    shortDescription: "Plantillas editables para crear contenido de alto impacto en Instagram y TikTok.",
    coverImageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=80",
    price: 24.0,
    currencyCode: "USD",
    guaranteeDays: 7,
    affiliateEnabled: true,
    affiliateCommissionPct: 45.0,
    affiliateApprovalMode: "AUTO",
    salesCount: 780,
    ratingAvg: 4.9,
    reviewsCount: 110,
    category: { name: "Redes y Marketing" },
    seller: {
      firstName: "Valeria",
      lastName: "Ríos",
      avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    },
  },
];

export const FALLBACK_CATEGORIES = [
  { id: "cat-1", slug: "prompts-ia", name: "Prompts IA", icon: "Bot", description: "Prompts optimizados para ChatGPT, Claude, Midjourney y SD" },
  { id: "cat-2", slug: "codigo-scripts", name: "Código y Scripts", icon: "Code", description: "Boilerplates, APIs, micro-servicios y scripts listos" },
  { id: "cat-3", slug: "cursos-online", name: "Cursos Online", icon: "Zap", description: "Masterclasses, bootcamps y capacitaciones en video" },
  { id: "cat-4", slug: "plantillas-web", name: "Plantillas Web", icon: "Palette", description: "Sistemas de diseño, UI kits y temas para Next.js y Tailwind" },
  { id: "cat-5", slug: "ebooks-guias", name: "Ebooks y Guías", icon: "Download", description: "Guías estratégicas y manuales en PDF" },
  { id: "cat-6", slug: "redes-marketing", name: "Redes y Marketing", icon: "Megaphone", description: "Packs de contenido, plantillas para reels y copys" },
  { id: "cat-7", slug: "finanzas-negocios", name: "Finanzas y Negocios", icon: "Briefcase", description: "Modelos financieros y hojas de cálculo" },
];

export const FALLBACK_LEADERS = [
  {
    rank: 1,
    userId: "demo-seller-1",
    name: "Ignacio Morales",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    countryCode: "UY",
    salesVolumeUsd: 148520.0,
    tier: {
      id: "GOLD",
      name: "Halcón Oro",
      badge: "🥇",
      minUsd: 100000,
      nextUsd: 500000,
      color: "#fbbf24",
      gradient: "from-yellow-500 to-amber-300",
      description: "Club de $100,000 USD. Creador y promotor de escala global.",
    },
  },
  {
    rank: 2,
    userId: "demo-seller-2",
    name: "Valeria Ríos",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    countryCode: "MX",
    salesVolumeUsd: 87400.0,
    tier: {
      id: "SILVER",
      name: "Halcón Plata",
      badge: "🥈",
      minUsd: 10000,
      nextUsd: 100000,
      color: "#e2e8f0",
      gradient: "from-slate-300 to-cyan-200",
      description: "Más de $10,000 USD generados. Estructura de alto rendimiento.",
    },
  },
  {
    rank: 3,
    userId: "demo-affiliate-1",
    name: "Gabriel López",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    countryCode: "AR",
    salesVolumeUsd: 32600.0,
    tier: {
      id: "SILVER",
      name: "Halcón Plata",
      badge: "🥈",
      minUsd: 10000,
      nextUsd: 100000,
      color: "#e2e8f0",
      gradient: "from-slate-300 to-cyan-200",
      description: "Más de $10,000 USD generados. Estructura de alto rendimiento.",
    },
  },
];
